server:
  port: 5050
  email-admin:
  password-email:
application:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-time: 864000
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: root
    password: minhtam123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin_management
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenminhtam01632.fetel@gmail.com
    password: xjoxgmzdldksingb


